GET http://localhost:3000/posts



### USERS
GET http://localhost:3000/users
### Post users
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "evin",
    "password": "123"
}

### Post login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name": "evin",
    "password": "123"
}